# Generated by Django 4.2 on 2023-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password1',
            field=models.CharField(default='10', max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(default='10', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
